include:
  - board: nice_nano/nrf52840/zmk
    shield: kometa_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: kometa_dongle
  - board: nice_nano/nrf52840/zmk
    shield: kometa_left
    snippet: zmk-usb-logging
    artifact-name: kometa_left
  - board: nice_nano/nrf52840/zmk
    shield: kometa_right
    snippet: zmk-usb-logging
    artifact-name: kometa_right
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset
