include:
  - board: nice_nano/nrf52840/zmk
    shield: kometa_left
    snippet: zmk-usb-logging
  - board: nice_nano/nrf52840/zmk
    shield: kometa_right
    snippet: zmk-usb-logging
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
